name: Demo Project
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with: 
             path: ~/.npm
             key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: run linter
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with: 
             path: ~/.npm
             key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        id: test-step
        run: npm test
      - name: Upload test reports
        if: failure() && steps.test-step.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
            name: test-reports
            path: test.json
  Build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3 
        with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build

        
  Deploy:
    needs: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: test-reports
      - name: output build artifacts
        run: ls -la 
      - name: Deploy to production
        run: echo "Deploying to production..."
  
  Report:
    needs: [lint, Deploy]
    if: failure() # Only run this job if either lint or Deploy fails
    runs-on: ubuntu-latest
    steps:
      - name: Generate report
        run: |
          echo "Generating report..."
          echo " {{ toJSON(github) }}"