name: Reusable workflow
on: 
    workflow_call:  # This allows the workflow to be called by other workflows
        inputs: # Define any inputs that the reusable workflow expects
            artifact-file:
                description: 'The name of the artifact to deploy'
                required: true  # This input is required when calling the workflow
                type: string  
                default: 'test-reports'  # Default value for the input if not provided         
         
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploying..."
            - name: Download build artifacts
              uses: actions/download-artifact@v8
              with:
                name: ${{ inputs.artifact-file }} # Use the input provided when calling the workflow
              